SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

# Unify target echoing
PRINT_TARGET = @echo "[make] --> $@"

.PHONY: clean
clean:  ## Remove autogenerated and downloaded files
	$(PRINT_TARGET)
	-rm -fr ./out/EFI ./out/bin

.PHONY: help
help:  ## Display this help
	@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	  | sort \
	  | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[0;32m%-30s\033[0m %s\n", $$1, $$2}'

.PHONY: lint
lint:  ## Run linters
	$(PRINT_TARGET)
	pre-commit run --all-files
	@echo "Linting property list files..."
	find "${CURDIR}" -name '*.plist' -print0 | xargs -0 -t -n1 plutil -lint

.PHONY: test
test: clean  ## Run tests
	$(PRINT_TARGET)
	bats ${CI:--tap} --timing --jobs 4 .

.PHONY: release
release:  ## Create RELEASE EFI variant
    @EFI_VARIANT=RELEASE ./build.sh

.PHONY: debug
debug:  ## Create DEBUG EFI variant
    @EFI_VARIANT=DEBUG ./build.sh
