name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "dry-run"
        default: "true"
        required: false
      log-level:
        description: "log-level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 5 * * Wed"

env:
  LOG_LEVEL: info
  DRY_RUN: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Override default config from dispatch variables
        run: |
          echo "DRY_RUN=${{ github.event.inputs.dry-run || env.DRY_RUN }}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${{ github.event.inputs.log-level || env.LOG_LEVEL }}" >> "${GITHUB_ENV}"

      - name: Renovate
        uses: renovatebot/github-action@v43.0.8
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GH_TOKEN_REPO }}
